// Code generated by protoc-gen-gogo.
// source: protos.proto
// DO NOT EDIT!

/*
Package shared is a generated protocol buffer package.

It is generated from these files:
	protos.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	AddRequest
	AddResponse
*/
package shared

import log "log"
import github_com_AsynkronIT_gam_cluster_grains "github.com/AsynkronIT/gam/cluster/grains"
import github_com_AsynkronIT_gam_actor "github.com/AsynkronIT/gam/actor"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var xHelloFactory func() Hello

func HelloFactory(factory func() Hello) {
	xHelloFactory = factory
}

func GetHelloGrain(id string) *HelloGrain {
	return &HelloGrain{inner: xHelloFactory()}
}

type Hello interface {
	SayHello(*HelloRequest) *HelloResponse
	Add(*AddRequest) *AddResponse
}
type HelloGrain struct {
	github_com_AsynkronIT_gam_cluster_grains.GrainMixin
	inner Hello
}

func (g *HelloGrain) SayHello(r *HelloRequest) *HelloResponse {
	return g.inner.SayHello(r)
}

func (g *HelloGrain) SayHelloChan(r *HelloRequest) <-chan *HelloResponse {
	c := make(chan *HelloResponse, 1)
	defer close(c)
	c <- g.inner.SayHello(r)
	return c
}

func (g *HelloGrain) Add(r *AddRequest) *AddResponse {
	return g.inner.Add(r)
}

func (g *HelloGrain) AddChan(r *AddRequest) <-chan *AddResponse {
	c := make(chan *AddResponse, 1)
	defer close(c)
	c <- g.inner.Add(r)
	return c
}

type HelloActor struct {
	inner Hello
}

func (a *HelloActor) Receive(ctx github_com_AsynkronIT_gam_actor.Context) {
	switch msg := ctx.Message().(type) {
	case *github_com_AsynkronIT_gam_cluster_grains.GrainRequest:
		switch msg.Method {
		case "SayHello":
			req := &HelloRequest{}
			proto.Unmarshal(msg.MessageData, req)
			a.inner.SayHello(req)
		case "Add":
			req := &AddRequest{}
			proto.Unmarshal(msg.MessageData, req)
			a.inner.Add(req)
		}
	default:
		log.Printf("Unknown message %v", msg)
	}
}
