// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v4.25.3
// source: protos.proto

package shared

import (
	fmt "fmt"
	actor "github.com/awevoke/protoactor-go/actor"
	cluster "github.com/awevoke/protoactor-go/cluster"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	time "time"
)

var xCounterFactory func() Counter

// CounterFactory produces a Counter
func CounterFactory(factory func() Counter) {
	xCounterFactory = factory
}

// GetCounterGrainClient instantiates a new CounterGrainClient with given Identity
func GetCounterGrainClient(c *cluster.Cluster, id string) *CounterGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &CounterGrainClient{Identity: id, cluster: c}
}

// GetCounterKind instantiates a new cluster.Kind for Counter
func GetCounterKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &CounterActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Counter", props)
	return kind
}

// NewCounterKind instantiates a new cluster.Kind for Counter
func NewCounterKind(factory func() Counter, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xCounterFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &CounterActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Counter", props)
	return kind
}

// Counter interfaces the services available to the Counter
type Counter interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	Increment(req *IncrementRequest, ctx cluster.GrainContext) (*CountResponse, error)
	GetCount(req *GetCountRequest, ctx cluster.GrainContext) (*CountResponse, error)
}

// CounterGrainClient holds the base data for the CounterGrain
type CounterGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// Increment requests the execution on to the cluster with CallOptions
func (g *CounterGrainClient) Increment(r *IncrementRequest, opts ...cluster.GrainCallOption) (*CountResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "Counter"), slog.String("method", "Increment"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Counter", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *CountResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// GetCount requests the execution on to the cluster with CallOptions
func (g *CounterGrainClient) GetCount(r *GetCountRequest, opts ...cluster.GrainCallOption) (*CountResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "Counter"), slog.String("method", "GetCount"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Counter", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *CountResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// CounterActor represents the actor structure
type CounterActor struct {
	ctx     cluster.GrainContext
	inner   Counter
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *CounterActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xCounterFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &IncrementRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] Increment(IncrementRequest) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.Increment(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		case 1:
			req := &GetCountRequest{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] GetCount(GetCountRequest) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.GetCount(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *CounterActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
