@startuml

title "Partition Sequence"

participant "IdentityLookup@node1" as lookup #LightGreen
participant "IdentityActor@node1" as id1     #LightGreen
participant "PlacementActor@node1" as place1 #LightGreen

participant "IdentityActor@node2" as id2     #Pink
participant "PlacementActor@node2" as place2 #Pink


lookup -> id1: send ActivationRequest
activate id1
    id1 -> id1: owner.address = chash(ClusterIdentity)
    activate id1

alt owner.address == self.address (owner = chash(id))
    id1 -> place1: forward ActivationRequest
    activate place1
        id1 <- place1: respond ActivationResponse
        deactivate place1
    deactivate id1
    lookup <- id1: respond ActivationResponse
else
    id1 -> id2: send ActivationRequest
    activate id2
        id2 -> id2:  owner.address = chash(ClusterIdentity)
        activate id2
            id2 -> place2: forward ActivationRequest
            deactivate id2
        deactivate id2
        activate place2
            id1 <- place2: respond ActivationResponse
            deactivate place2
        lookup <- id1: respond ActivationResponse
    deactivate id1
end

@enduml