version: "3"
services:
  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"
    command: ["-js"]

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  consul:
    image: hashicorp/consul:1.19
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-client=0.0.0.0"]
