// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	AddItemCommand
	AddedItemEvent
	RenameCommand
	RenamedEvent
	DumpCommand
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// user messages
type AddItemCommand struct {
	Item string `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *AddItemCommand) Reset()                    { *m = AddItemCommand{} }
func (m *AddItemCommand) String() string            { return proto.CompactTextString(m) }
func (*AddItemCommand) ProtoMessage()               {}
func (*AddItemCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddedItemEvent struct {
	Item string `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *AddedItemEvent) Reset()                    { *m = AddedItemEvent{} }
func (m *AddedItemEvent) String() string            { return proto.CompactTextString(m) }
func (*AddedItemEvent) ProtoMessage()               {}
func (*AddedItemEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RenameCommand struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RenameCommand) Reset()                    { *m = RenameCommand{} }
func (m *RenameCommand) String() string            { return proto.CompactTextString(m) }
func (*RenameCommand) ProtoMessage()               {}
func (*RenameCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RenamedEvent struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RenamedEvent) Reset()                    { *m = RenamedEvent{} }
func (m *RenamedEvent) String() string            { return proto.CompactTextString(m) }
func (*RenamedEvent) ProtoMessage()               {}
func (*RenamedEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DumpCommand struct {
}

func (m *DumpCommand) Reset()                    { *m = DumpCommand{} }
func (m *DumpCommand) String() string            { return proto.CompactTextString(m) }
func (*DumpCommand) ProtoMessage()               {}
func (*DumpCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*AddItemCommand)(nil), "messages.AddItemCommand")
	proto.RegisterType((*AddedItemEvent)(nil), "messages.AddedItemEvent")
	proto.RegisterType((*RenameCommand)(nil), "messages.RenameCommand")
	proto.RegisterType((*RenamedEvent)(nil), "messages.RenamedEvent")
	proto.RegisterType((*DumpCommand)(nil), "messages.DumpCommand")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x54,
	0xb8, 0xf8, 0x1c, 0x53, 0x52, 0x3c, 0x4b, 0x52, 0x73, 0x9d, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52,
	0x84, 0x84, 0xb8, 0x58, 0x32, 0x81, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b,
	0xaa, 0x2a, 0x15, 0xac, 0xce, 0xb5, 0x2c, 0x35, 0xaf, 0x04, 0xab, 0x2a, 0x65, 0x2e, 0xde, 0xa0,
	0xd4, 0xbc, 0xc4, 0xdc, 0x54, 0x24, 0xa3, 0x40, 0x5c, 0x98, 0x22, 0x10, 0x5b, 0x49, 0x89, 0x8b,
	0x07, 0xa2, 0x28, 0x05, 0x6e, 0x10, 0x86, 0x1a, 0x5e, 0x2e, 0x6e, 0x97, 0xd2, 0xdc, 0x02, 0xa8,
	0x31, 0x49, 0x6c, 0x60, 0x47, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x45, 0x9b, 0xce, 0x0d,
	0xc6, 0x00, 0x00, 0x00,
}
