// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v4.25.3
// source: protos.proto

package shared

import (
	fmt "fmt"
	actor "github.com/awevoke/protoactor-go/actor"
	cluster "github.com/awevoke/protoactor-go/cluster"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
	time "time"
)

var xSensorFactory func() Sensor

// SensorFactory produces a Sensor
func SensorFactory(factory func() Sensor) {
	xSensorFactory = factory
}

// GetSensorGrainClient instantiates a new SensorGrainClient with given Identity
func GetSensorGrainClient(c *cluster.Cluster, id string) *SensorGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &SensorGrainClient{Identity: id, cluster: c}
}

// GetSensorKind instantiates a new cluster.Kind for Sensor
func GetSensorKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SensorActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("Sensor", props)
	return kind
}

// NewSensorKind instantiates a new cluster.Kind for Sensor
func NewSensorKind(factory func() Sensor, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xSensorFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SensorActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("Sensor", props)
	return kind
}

// Sensor interfaces the services available to the Sensor
type Sensor interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	HandleReading(req *SensorReading, ctx cluster.GrainContext) (*Ack, error)
}

// SensorGrainClient holds the base data for the SensorGrain
type SensorGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// HandleReading requests the execution on to the cluster with CallOptions
func (g *SensorGrainClient) HandleReading(r *SensorReading, opts ...cluster.GrainCallOption) (*Ack, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "Sensor"), slog.String("method", "HandleReading"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "Sensor", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *Ack:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// SensorActor represents the actor structure
type SensorActor struct {
	ctx     cluster.GrainContext
	inner   Sensor
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *SensorActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xSensorFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &SensorReading{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] HandleReading(SensorReading) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.HandleReading(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *SensorActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
