// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pubsub_cluster.proto

package cluster_test_tool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPublished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPublished) Reset() {
	*x = DataPublished{}
	mi := &file_pubsub_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPublished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPublished) ProtoMessage() {}

func (x *DataPublished) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPublished.ProtoReflect.Descriptor instead.
func (*DataPublished) Descriptor() ([]byte, []int) {
	return file_pubsub_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *DataPublished) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pubsub_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pubsub_cluster_proto_rawDescGZIP(), []int{1}
}

var File_pubsub_cluster_proto protoreflect.FileDescriptor

const file_pubsub_cluster_proto_rawDesc = "" +
	"\n" +
	"\x14pubsub_cluster.proto\x12\x11cluster_test_tool\"#\n" +
	"\rDataPublished\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"\n" +
	"\n" +
	"\bResponseB=Z;/github.com/awevoke/protoactor-go/cluster/cluster_test_toolb\x06proto3"

var (
	file_pubsub_cluster_proto_rawDescOnce sync.Once
	file_pubsub_cluster_proto_rawDescData []byte
)

func file_pubsub_cluster_proto_rawDescGZIP() []byte {
	file_pubsub_cluster_proto_rawDescOnce.Do(func() {
		file_pubsub_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsub_cluster_proto_rawDesc), len(file_pubsub_cluster_proto_rawDesc)))
	})
	return file_pubsub_cluster_proto_rawDescData
}

var file_pubsub_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pubsub_cluster_proto_goTypes = []any{
	(*DataPublished)(nil), // 0: cluster_test_tool.DataPublished
	(*Response)(nil),      // 1: cluster_test_tool.Response
}
var file_pubsub_cluster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubsub_cluster_proto_init() }
func file_pubsub_cluster_proto_init() {
	if File_pubsub_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsub_cluster_proto_rawDesc), len(file_pubsub_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubsub_cluster_proto_goTypes,
		DependencyIndexes: file_pubsub_cluster_proto_depIdxs,
		MessageInfos:      file_pubsub_cluster_proto_msgTypes,
	}.Build()
	File_pubsub_cluster_proto = out.File
	file_pubsub_cluster_proto_goTypes = nil
	file_pubsub_cluster_proto_depIdxs = nil
}
