name: Generate Sponsors README
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update sponsors list"
          file_pattern: README.md
